// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package corepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Certificate struct {
	Serial               []byte         `protobuf:"bytes,9,opt,name=Serial,proto3" json:"Serial,omitempty"`
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CertDER              []byte         `protobuf:"bytes,2,opt,name=certDER,proto3" json:"certDER,omitempty"`
	Identifiers          []string       `protobuf:"bytes,3,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	OrderId              string         `protobuf:"bytes,4,opt,name=orderId,proto3" json:"orderId,omitempty"`
	CaCert               *CaCertificate `protobuf:"bytes,5,opt,name=CaCert,proto3" json:"CaCert,omitempty"`
	RevocationTime       string         `protobuf:"bytes,7,opt,name=RevocationTime,proto3" json:"RevocationTime,omitempty"`
	IssuerNameHash       []byte         `protobuf:"bytes,6,opt,name=IssuerNameHash,proto3" json:"IssuerNameHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Certificate) Reset()         { *m = Certificate{} }
func (m *Certificate) String() string { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()    {}
func (*Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{0}
}
func (m *Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Certificate.Unmarshal(m, b)
}
func (m *Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Certificate.Marshal(b, m, deterministic)
}
func (dst *Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certificate.Merge(dst, src)
}
func (m *Certificate) XXX_Size() int {
	return xxx_messageInfo_Certificate.Size(m)
}
func (m *Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_Certificate proto.InternalMessageInfo

func (m *Certificate) GetSerial() []byte {
	if m != nil {
		return m.Serial
	}
	return nil
}

func (m *Certificate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Certificate) GetCertDER() []byte {
	if m != nil {
		return m.CertDER
	}
	return nil
}

func (m *Certificate) GetIdentifiers() []string {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *Certificate) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Certificate) GetCaCert() *CaCertificate {
	if m != nil {
		return m.CaCert
	}
	return nil
}

func (m *Certificate) GetRevocationTime() string {
	if m != nil {
		return m.RevocationTime
	}
	return ""
}

func (m *Certificate) GetIssuerNameHash() []byte {
	if m != nil {
		return m.IssuerNameHash
	}
	return nil
}

type CaCertificate struct {
	NameHash             []byte   `protobuf:"bytes,1,opt,name=NameHash,proto3" json:"NameHash,omitempty"`
	CertDER              []byte   `protobuf:"bytes,2,opt,name=certDER,proto3" json:"certDER,omitempty"`
	WillIssue            bool     `protobuf:"varint,3,opt,name=willIssue,proto3" json:"willIssue,omitempty"`
	CommonName           string   `protobuf:"bytes,4,opt,name=CommonName,proto3" json:"CommonName,omitempty"`
	Id                   string   `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	CaCertId             string   `protobuf:"bytes,6,opt,name=CaCertId,proto3" json:"CaCertId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaCertificate) Reset()         { *m = CaCertificate{} }
func (m *CaCertificate) String() string { return proto.CompactTextString(m) }
func (*CaCertificate) ProtoMessage()    {}
func (*CaCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{1}
}
func (m *CaCertificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaCertificate.Unmarshal(m, b)
}
func (m *CaCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaCertificate.Marshal(b, m, deterministic)
}
func (dst *CaCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaCertificate.Merge(dst, src)
}
func (m *CaCertificate) XXX_Size() int {
	return xxx_messageInfo_CaCertificate.Size(m)
}
func (m *CaCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_CaCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_CaCertificate proto.InternalMessageInfo

func (m *CaCertificate) GetNameHash() []byte {
	if m != nil {
		return m.NameHash
	}
	return nil
}

func (m *CaCertificate) GetCertDER() []byte {
	if m != nil {
		return m.CertDER
	}
	return nil
}

func (m *CaCertificate) GetWillIssue() bool {
	if m != nil {
		return m.WillIssue
	}
	return false
}

func (m *CaCertificate) GetCommonName() string {
	if m != nil {
		return m.CommonName
	}
	return ""
}

func (m *CaCertificate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CaCertificate) GetCaCertId() string {
	if m != nil {
		return m.CaCertId
	}
	return ""
}

type IdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{2}
}
func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (dst *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(dst, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type IdResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdResponse) Reset()         { *m = IdResponse{} }
func (m *IdResponse) String() string { return proto.CompactTextString(m) }
func (*IdResponse) ProtoMessage()    {}
func (*IdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{3}
}
func (m *IdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdResponse.Unmarshal(m, b)
}
func (m *IdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdResponse.Marshal(b, m, deterministic)
}
func (dst *IdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdResponse.Merge(dst, src)
}
func (m *IdResponse) XXX_Size() int {
	return xxx_messageInfo_IdResponse.Size(m)
}
func (m *IdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IdResponse proto.InternalMessageInfo

func (m *IdResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Authorization struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpiresDate          string       `protobuf:"bytes,2,opt,name=expiresDate,proto3" json:"expiresDate,omitempty"`
	Status               string       `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Identifier           *Identifier  `protobuf:"bytes,4,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Challenges           []*Challenge `protobuf:"bytes,5,rep,name=Challenges,proto3" json:"Challenges,omitempty"`
	AccountId            string       `protobuf:"bytes,6,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Authorization) Reset()         { *m = Authorization{} }
func (m *Authorization) String() string { return proto.CompactTextString(m) }
func (*Authorization) ProtoMessage()    {}
func (*Authorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{4}
}
func (m *Authorization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authorization.Unmarshal(m, b)
}
func (m *Authorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authorization.Marshal(b, m, deterministic)
}
func (dst *Authorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authorization.Merge(dst, src)
}
func (m *Authorization) XXX_Size() int {
	return xxx_messageInfo_Authorization.Size(m)
}
func (m *Authorization) XXX_DiscardUnknown() {
	xxx_messageInfo_Authorization.DiscardUnknown(m)
}

var xxx_messageInfo_Authorization proto.InternalMessageInfo

func (m *Authorization) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Authorization) GetExpiresDate() string {
	if m != nil {
		return m.ExpiresDate
	}
	return ""
}

func (m *Authorization) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Authorization) GetIdentifier() *Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *Authorization) GetChallenges() []*Challenge {
	if m != nil {
		return m.Challenges
	}
	return nil
}

func (m *Authorization) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type Identifier struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{5}
}
func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (dst *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(dst, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Identifier) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Challenge struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Validated            string   `protobuf:"bytes,5,opt,name=validated,proto3" json:"validated,omitempty"`
	Problem              *Problem `protobuf:"bytes,6,opt,name=problem,proto3" json:"problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Challenge) Reset()         { *m = Challenge{} }
func (m *Challenge) String() string { return proto.CompactTextString(m) }
func (*Challenge) ProtoMessage()    {}
func (*Challenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{6}
}
func (m *Challenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Challenge.Unmarshal(m, b)
}
func (m *Challenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Challenge.Marshal(b, m, deterministic)
}
func (dst *Challenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Challenge.Merge(dst, src)
}
func (m *Challenge) XXX_Size() int {
	return xxx_messageInfo_Challenge.Size(m)
}
func (m *Challenge) XXX_DiscardUnknown() {
	xxx_messageInfo_Challenge.DiscardUnknown(m)
}

var xxx_messageInfo_Challenge proto.InternalMessageInfo

func (m *Challenge) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Challenge) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Challenge) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Challenge) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Challenge) GetValidated() string {
	if m != nil {
		return m.Validated
	}
	return ""
}

func (m *Challenge) GetProblem() *Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{7}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Contact              []string `protobuf:"bytes,4,rep,name=contact,proto3" json:"contact,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ExternalIdentifier   string   `protobuf:"bytes,6,opt,name=externalIdentifier,proto3" json:"externalIdentifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{8}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Account) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Account) GetContact() []string {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *Account) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Account) GetExternalIdentifier() string {
	if m != nil {
		return m.ExternalIdentifier
	}
	return ""
}

type Order struct {
	Id                     string           `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Authz                  []*Authorization `protobuf:"bytes,2,rep,name=authz,proto3" json:"authz,omitempty"`
	Status                 string           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ExpiresDate            string           `protobuf:"bytes,4,opt,name=expiresDate,proto3" json:"expiresDate,omitempty"`
	CertificateId          string           `protobuf:"bytes,5,opt,name=certificateId,proto3" json:"certificateId,omitempty"`
	RequestedNotBeforeDate string           `protobuf:"bytes,6,opt,name=requestedNotBeforeDate,proto3" json:"requestedNotBeforeDate,omitempty"`
	RequestedNotAfterDate  string           `protobuf:"bytes,7,opt,name=requestedNotAfterDate,proto3" json:"requestedNotAfterDate,omitempty"`
	Error                  *Problem         `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	AccountId              string           `protobuf:"bytes,10,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}         `json:"-"`
	XXX_unrecognized       []byte           `json:"-"`
	XXX_sizecache          int32            `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{9}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetAuthz() []*Authorization {
	if m != nil {
		return m.Authz
	}
	return nil
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetExpiresDate() string {
	if m != nil {
		return m.ExpiresDate
	}
	return ""
}

func (m *Order) GetCertificateId() string {
	if m != nil {
		return m.CertificateId
	}
	return ""
}

func (m *Order) GetRequestedNotBeforeDate() string {
	if m != nil {
		return m.RequestedNotBeforeDate
	}
	return ""
}

func (m *Order) GetRequestedNotAfterDate() string {
	if m != nil {
		return m.RequestedNotAfterDate
	}
	return ""
}

func (m *Order) GetError() *Problem {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Order) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type Problem struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Problem) Reset()         { *m = Problem{} }
func (m *Problem) String() string { return proto.CompactTextString(m) }
func (*Problem) ProtoMessage()    {}
func (*Problem) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{10}
}
func (m *Problem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Problem.Unmarshal(m, b)
}
func (m *Problem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Problem.Marshal(b, m, deterministic)
}
func (dst *Problem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Problem.Merge(dst, src)
}
func (m *Problem) XXX_Size() int {
	return xxx_messageInfo_Problem.Size(m)
}
func (m *Problem) XXX_DiscardUnknown() {
	xxx_messageInfo_Problem.DiscardUnknown(m)
}

var xxx_messageInfo_Problem proto.InternalMessageInfo

func (m *Problem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Problem) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type CRL struct {
	CA                   string   `protobuf:"bytes,1,opt,name=CA,proto3" json:"CA,omitempty"`
	CRL                  []byte   `protobuf:"bytes,2,opt,name=CRL,proto3" json:"CRL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CRL) Reset()         { *m = CRL{} }
func (m *CRL) String() string { return proto.CompactTextString(m) }
func (*CRL) ProtoMessage()    {}
func (*CRL) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{11}
}
func (m *CRL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CRL.Unmarshal(m, b)
}
func (m *CRL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CRL.Marshal(b, m, deterministic)
}
func (dst *CRL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CRL.Merge(dst, src)
}
func (m *CRL) XXX_Size() int {
	return xxx_messageInfo_CRL.Size(m)
}
func (m *CRL) XXX_DiscardUnknown() {
	xxx_messageInfo_CRL.DiscardUnknown(m)
}

var xxx_messageInfo_CRL proto.InternalMessageInfo

func (m *CRL) GetCA() string {
	if m != nil {
		return m.CA
	}
	return ""
}

func (m *CRL) GetCRL() []byte {
	if m != nil {
		return m.CRL
	}
	return nil
}

type RevokedCertificate struct {
	Serial               []byte   `protobuf:"bytes,1,opt,name=Serial,proto3" json:"Serial,omitempty"`
	RevocationTime       string   `protobuf:"bytes,2,opt,name=RevocationTime,proto3" json:"RevocationTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokedCertificate) Reset()         { *m = RevokedCertificate{} }
func (m *RevokedCertificate) String() string { return proto.CompactTextString(m) }
func (*RevokedCertificate) ProtoMessage()    {}
func (*RevokedCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{12}
}
func (m *RevokedCertificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokedCertificate.Unmarshal(m, b)
}
func (m *RevokedCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokedCertificate.Marshal(b, m, deterministic)
}
func (dst *RevokedCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokedCertificate.Merge(dst, src)
}
func (m *RevokedCertificate) XXX_Size() int {
	return xxx_messageInfo_RevokedCertificate.Size(m)
}
func (m *RevokedCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokedCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_RevokedCertificate proto.InternalMessageInfo

func (m *RevokedCertificate) GetSerial() []byte {
	if m != nil {
		return m.Serial
	}
	return nil
}

func (m *RevokedCertificate) GetRevocationTime() string {
	if m != nil {
		return m.RevocationTime
	}
	return ""
}

type RevokedCertificates struct {
	RevokedCerts         []*RevokedCertificate `protobuf:"bytes,1,rep,name=revokedCerts,proto3" json:"revokedCerts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RevokedCertificates) Reset()         { *m = RevokedCertificates{} }
func (m *RevokedCertificates) String() string { return proto.CompactTextString(m) }
func (*RevokedCertificates) ProtoMessage()    {}
func (*RevokedCertificates) Descriptor() ([]byte, []int) {
	return fileDescriptor_core_d584ea73a67a81b9, []int{13}
}
func (m *RevokedCertificates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokedCertificates.Unmarshal(m, b)
}
func (m *RevokedCertificates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokedCertificates.Marshal(b, m, deterministic)
}
func (dst *RevokedCertificates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokedCertificates.Merge(dst, src)
}
func (m *RevokedCertificates) XXX_Size() int {
	return xxx_messageInfo_RevokedCertificates.Size(m)
}
func (m *RevokedCertificates) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokedCertificates.DiscardUnknown(m)
}

var xxx_messageInfo_RevokedCertificates proto.InternalMessageInfo

func (m *RevokedCertificates) GetRevokedCerts() []*RevokedCertificate {
	if m != nil {
		return m.RevokedCerts
	}
	return nil
}

func init() {
	proto.RegisterType((*Certificate)(nil), "core.Certificate")
	proto.RegisterType((*CaCertificate)(nil), "core.CaCertificate")
	proto.RegisterType((*IdRequest)(nil), "core.IdRequest")
	proto.RegisterType((*IdResponse)(nil), "core.IdResponse")
	proto.RegisterType((*Authorization)(nil), "core.Authorization")
	proto.RegisterType((*Identifier)(nil), "core.Identifier")
	proto.RegisterType((*Challenge)(nil), "core.Challenge")
	proto.RegisterType((*Empty)(nil), "core.Empty")
	proto.RegisterType((*Account)(nil), "core.Account")
	proto.RegisterType((*Order)(nil), "core.Order")
	proto.RegisterType((*Problem)(nil), "core.Problem")
	proto.RegisterType((*CRL)(nil), "core.CRL")
	proto.RegisterType((*RevokedCertificate)(nil), "core.RevokedCertificate")
	proto.RegisterType((*RevokedCertificates)(nil), "core.RevokedCertificates")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_core_d584ea73a67a81b9) }

var fileDescriptor_core_d584ea73a67a81b9 = []byte{
	// 764 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xcd, 0x6e, 0xc3, 0x44,
	0x10, 0x96, 0x9d, 0xbf, 0x7a, 0xd2, 0x94, 0x6a, 0x4b, 0xab, 0x15, 0x54, 0xc8, 0x32, 0x88, 0x06,
	0x21, 0x05, 0x14, 0xa0, 0x27, 0x2e, 0xa9, 0x5b, 0x89, 0x48, 0x55, 0x41, 0xdb, 0x9e, 0xb8, 0x6d,
	0xed, 0x29, 0xb1, 0xe2, 0x78, 0xc3, 0x7a, 0x53, 0xda, 0x3e, 0x01, 0x0f, 0xc2, 0x09, 0x0e, 0x3c,
	0x0c, 0x37, 0x9e, 0x06, 0xed, 0x7a, 0x6d, 0xc7, 0x71, 0xca, 0xcd, 0xf3, 0xcd, 0xec, 0x78, 0x66,
	0xbe, 0x6f, 0x76, 0x01, 0x22, 0x21, 0x71, 0xb2, 0x96, 0x42, 0x09, 0xd2, 0xd5, 0xdf, 0xc1, 0xef,
	0x2e, 0x0c, 0x43, 0x94, 0x2a, 0x79, 0x4a, 0x22, 0xae, 0x90, 0x9c, 0x41, 0xff, 0x1e, 0x65, 0xc2,
	0x53, 0xea, 0xf9, 0xce, 0xf8, 0x90, 0x59, 0x8b, 0x1c, 0x81, 0x9b, 0xc4, 0xd4, 0xf1, 0x9d, 0xb1,
	0xc7, 0xdc, 0x24, 0x26, 0x14, 0x06, 0x11, 0x4a, 0x75, 0x7d, 0xc3, 0xa8, 0x6b, 0x02, 0x4b, 0x93,
	0xf8, 0x30, 0x4c, 0x62, 0xcc, 0x74, 0x46, 0x94, 0x39, 0xed, 0xf8, 0x9d, 0xb1, 0xc7, 0xb6, 0x21,
	0x7d, 0x56, 0xc8, 0x18, 0xe5, 0x3c, 0xa6, 0x5d, 0x93, 0xb0, 0x34, 0xc9, 0x97, 0xd0, 0x0f, 0xb9,
	0x2e, 0x87, 0xf6, 0x7c, 0x67, 0x3c, 0x9c, 0x9e, 0x4c, 0x4c, 0xc1, 0x05, 0x66, 0x4b, 0x64, 0x36,
	0x84, 0x7c, 0x0e, 0x47, 0x0c, 0x9f, 0x45, 0xc4, 0x55, 0x22, 0xb2, 0x87, 0x64, 0x85, 0x74, 0x60,
	0xb2, 0xed, 0xa0, 0x3a, 0x6e, 0x9e, 0xe7, 0x1b, 0x94, 0x77, 0x7c, 0x85, 0x3f, 0xf0, 0x7c, 0x41,
	0xfb, 0xa6, 0xe2, 0x1d, 0x34, 0xf8, 0xdb, 0x81, 0x51, 0xe3, 0x4f, 0xe4, 0x23, 0x38, 0xa8, 0xce,
	0x38, 0xe6, 0x4c, 0x65, 0xff, 0xcf, 0x00, 0xce, 0xc1, 0xfb, 0x2d, 0x49, 0x53, 0x93, 0x9d, 0x76,
	0x7c, 0x67, 0x7c, 0xc0, 0x6a, 0x80, 0x7c, 0x02, 0x10, 0x8a, 0xd5, 0x4a, 0x64, 0x3a, 0x93, 0xed,
	0x7f, 0x0b, 0xd1, 0x83, 0x9e, 0xc7, 0xa6, 0x7d, 0x8f, 0xb9, 0xf3, 0x58, 0xd7, 0x50, 0x14, 0x35,
	0x8f, 0x4d, 0xdd, 0x1e, 0xab, 0xec, 0xe0, 0x63, 0xf0, 0xe6, 0x31, 0xc3, 0x5f, 0x37, 0x98, 0xab,
	0x5d, 0x86, 0x82, 0x73, 0x00, 0xed, 0xcc, 0xd7, 0x22, 0xcb, 0xb1, 0xe5, 0xfd, 0xd7, 0x81, 0xd1,
	0x6c, 0xa3, 0x16, 0x42, 0x26, 0x6f, 0x66, 0x54, 0x2d, 0x86, 0x7d, 0x18, 0xe2, 0xcb, 0x3a, 0x91,
	0x98, 0x5f, 0x73, 0x85, 0xa6, 0x49, 0x8f, 0x6d, 0x43, 0x5a, 0x2b, 0xb9, 0xe2, 0x6a, 0x93, 0x9b,
	0x2e, 0x3d, 0x66, 0x2d, 0xf2, 0x35, 0x40, 0x4d, 0xb7, 0x69, 0x71, 0x38, 0x3d, 0x2e, 0x98, 0x9c,
	0x57, 0x38, 0xdb, 0x8a, 0x21, 0x5f, 0x01, 0x84, 0x0b, 0x9e, 0xa6, 0x98, 0xfd, 0x82, 0x39, 0xed,
	0xf9, 0x9d, 0xf1, 0x70, 0xfa, 0x81, 0xe5, 0xbe, 0xc4, 0xd9, 0x56, 0x88, 0x9e, 0xf1, 0x2c, 0x8a,
	0xc4, 0x26, 0xab, 0xc7, 0x52, 0x03, 0xc1, 0xa5, 0x6e, 0xbd, 0x4a, 0x4e, 0xa0, 0xab, 0x5e, 0xd7,
	0x68, 0x5b, 0x33, 0xdf, 0xe4, 0x43, 0xe8, 0x3d, 0xf3, 0x74, 0x53, 0xb6, 0x55, 0x18, 0xc1, 0x1f,
	0x0e, 0x78, 0xd5, 0x4f, 0x2c, 0x13, 0x4e, 0xc5, 0x44, 0x99, 0xc7, 0x6d, 0xe6, 0x51, 0x62, 0x89,
	0x99, 0x9d, 0x40, 0x61, 0x6c, 0x0d, 0xa6, 0xdb, 0x18, 0xcc, 0x39, 0x78, 0xcf, 0x3c, 0x4d, 0x62,
	0xae, 0xb0, 0xa4, 0xb8, 0x06, 0xc8, 0x05, 0x0c, 0xd6, 0x52, 0x3c, 0xa6, 0xb8, 0x32, 0x1d, 0x0d,
	0xa7, 0xa3, 0x62, 0x02, 0x3f, 0x15, 0x20, 0x2b, 0xbd, 0xc1, 0x00, 0x7a, 0x37, 0xab, 0xb5, 0x7a,
	0x0d, 0xfe, 0x72, 0x60, 0x60, 0xbb, 0x6e, 0x55, 0x7b, 0x0c, 0x9d, 0x25, 0xbe, 0x5a, 0x6d, 0xea,
	0xcf, 0x77, 0xe9, 0xd2, 0x4a, 0x16, 0x99, 0xe2, 0x91, 0xa2, 0x5d, 0xb3, 0xac, 0xa5, 0xa9, 0xeb,
	0x8d, 0x24, 0xea, 0xe2, 0x66, 0xaa, 0xac, 0xb7, 0x02, 0xc8, 0x04, 0x08, 0xbe, 0x28, 0x94, 0x19,
	0x4f, 0xeb, 0x69, 0x5b, 0x32, 0xf6, 0x78, 0x82, 0x7f, 0x5c, 0xe8, 0xfd, 0xa8, 0x17, 0xbd, 0x55,
	0xeb, 0x17, 0xd0, 0xe3, 0x1b, 0xb5, 0x78, 0xa3, 0xae, 0x61, 0xde, 0x6e, 0x7d, 0x43, 0x9e, 0xac,
	0x88, 0x78, 0xb7, 0x89, 0x1d, 0xb5, 0x76, 0xdb, 0x6a, 0xfd, 0x0c, 0x46, 0x51, 0xbd, 0xdb, 0xd5,
	0x8e, 0x35, 0x41, 0x72, 0x09, 0x67, 0xb2, 0x58, 0x28, 0x8c, 0xef, 0x84, 0xba, 0xc2, 0x27, 0x21,
	0xd1, 0xa4, 0x2c, 0x1a, 0x7b, 0xc7, 0x4b, 0xbe, 0x85, 0xd3, 0x6d, 0xcf, 0xec, 0x49, 0xa1, 0x34,
	0xc7, 0x8a, 0x3b, 0x69, 0xbf, 0x93, 0x7c, 0x0a, 0x3d, 0x94, 0x52, 0x48, 0x7a, 0xb0, 0x8f, 0xf0,
	0xc2, 0xd7, 0xd4, 0x3a, 0xec, 0x6a, 0xfd, 0x3b, 0x18, 0xd8, 0xf8, 0xbd, 0x42, 0x3f, 0x83, 0x7e,
	0x8c, 0x8a, 0x27, 0xa9, 0x95, 0xad, 0xb5, 0x82, 0x0b, 0xe8, 0x84, 0xec, 0x56, 0x33, 0x11, 0xce,
	0x4a, 0x26, 0xc2, 0x99, 0x56, 0x4d, 0xc8, 0x6e, 0x4b, 0xd5, 0x84, 0xec, 0x36, 0x78, 0x00, 0xa2,
	0xef, 0xd3, 0x25, 0xc6, 0xfb, 0x9f, 0x09, 0xa7, 0xf1, 0x4c, 0xb4, 0xef, 0x64, 0x77, 0xdf, 0x9d,
	0x1c, 0xdc, 0xc3, 0x49, 0x3b, 0x6b, 0x4e, 0xbe, 0x87, 0x43, 0x59, 0xc3, 0x39, 0x75, 0x8c, 0x1e,
	0x68, 0x31, 0x96, 0xf6, 0x01, 0xd6, 0x88, 0xbe, 0x3a, 0xfd, 0xb9, 0xaf, 0x03, 0xd7, 0x8f, 0x7f,
	0xba, 0x70, 0x25, 0x93, 0x68, 0x39, 0x09, 0x85, 0xc4, 0xc7, 0xbe, 0x79, 0xef, 0xbe, 0xf9, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0x8b, 0xd8, 0x93, 0xd9, 0xfd, 0x06, 0x00, 0x00,
}
